// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whatnot.proto

package transports

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lease struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Absolutepath         string   `protobuf:"bytes,3,opt,name=absolutepath,proto3" json:"absolutepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{0}
}

func (m *Lease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lease.Unmarshal(m, b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return xxx_messageInfo_Lease.Size(m)
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lease) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Lease) GetAbsolutepath() string {
	if m != nil {
		return m.Absolutepath
	}
	return ""
}

func init() {
	proto.RegisterType((*Lease)(nil), "tutorial.Lease")
}

func init() { proto.RegisterFile("whatnot.proto", fileDescriptor_7e1fe3d4eec11dd6) }

var fileDescriptor_7e1fe3d4eec11dd6 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xce, 0x31, 0x0b, 0xc2, 0x30,
	0x14, 0x04, 0x60, 0x6a, 0x55, 0x6a, 0xd0, 0x25, 0x53, 0x71, 0x2a, 0x9d, 0x3a, 0x35, 0x88, 0xff,
	0xc0, 0xd9, 0xa9, 0xa3, 0x4e, 0x2f, 0x6d, 0xb0, 0x85, 0x36, 0xaf, 0xe4, 0x5d, 0xf0, 0xef, 0x0b,
	0x41, 0x04, 0xb7, 0xbb, 0x83, 0x83, 0x4f, 0x9d, 0xde, 0x23, 0xc1, 0x33, 0xda, 0x35, 0x30, 0x58,
	0x17, 0x88, 0xe0, 0x30, 0xd1, 0x5c, 0x3f, 0xd5, 0xee, 0xee, 0x48, 0x9c, 0xd6, 0x6a, 0xeb, 0x69,
	0x71, 0x65, 0x56, 0x65, 0xcd, 0xa1, 0x4b, 0x59, 0x9f, 0x55, 0x31, 0xc4, 0x40, 0x98, 0xd8, 0x97,
	0x9b, 0x2a, 0x6b, 0xf2, 0xee, 0xd7, 0x75, 0xad, 0x8e, 0x64, 0x85, 0xe7, 0x08, 0xb7, 0x12, 0xc6,
	0x32, 0x4f, 0xbf, 0xbf, 0xed, 0x76, 0x79, 0x98, 0xd7, 0x84, 0x31, 0xda, 0xb6, 0xe7, 0xc5, 0x0c,
	0x04, 0xb2, 0x8e, 0x04, 0xe6, 0x8b, 0x31, 0xfd, 0x1c, 0x05, 0x2e, 0x18, 0x04, 0xf2, 0xb2, 0x72,
	0x80, 0xd8, 0x7d, 0x02, 0x5e, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0xd4, 0x91, 0xb6, 0xb1,
	0x00, 0x00, 0x00,
}
